import { BROKER_PROTOCOL_VERSION } from "./version";

export const agentUsageGuide = {
  brokerProtocolVersion: BROKER_PROTOCOL_VERSION,
  purpose:
    "Use GenUI Popup Broker when an AI agent needs to show a local visual popup. The agent generates OpenUI Lang; the CLI/broker validates, stores, and renders it.",
  preferredFlow: [
    "Run `genui prompt-spec` to learn the OpenUI Lang syntax and available components.",
    "Use `genui examples` for known-good starter OpenUI Lang.",
    "Generate OpenUI Lang in the agent. Do not send a natural-language UI request to the broker.",
    "Validate the generated OpenUI Lang with `genui validate --openui-lang-file <file>`.",
    "Open the popup with `genui popup --openui-lang-file <file> --title <title> --agent-id <agent>`.",
    "Use `--wait` when the workflow needs a completion, cancellation, close, or failure result. Components with `actionId` return events in `completion.payload`.",
    "Use `genui components` for a concise component catalog.",
    "Use `genui artifacts` to inspect saved UI and `genui replay --artifact-id <artifactId>` to reopen it.",
    "Close the popup with `genui close --popup-id <popupId>` when it is no longer useful.",
  ],
  cli: {
    agentInstructions: "genui agent-instructions",
    promptSpec: "genui prompt-spec",
    examples: "genui examples",
    validate: "genui validate --openui-lang-file ui.openui",
    components: "genui components",
    open:
      "genui popup --agent-id <agent> --title <title> --size review --openui-lang-file ui.openui",
    openFromStdin:
      "cat ui.openui | genui popup --agent-id <agent> --title <title> --stdin-openui",
    openAndWait:
      "genui popup --agent-id <agent> --title <title> --openui-lang-file ui.openui --wait",
    popups: "genui popups",
    artifacts: "genui artifacts --limit 20",
    artifact: "genui artifact --artifact-id <artifactId>",
    replay: "genui replay --artifact-id <artifactId>",
    prune: "genui prune --max-artifacts 50",
    close: "genui close --popup-id <popupId>",
    status: "genui status",
  },
  recommendedComponents: [
    "MetricGrid",
    "Stat",
    "KeyValuePanel",
    "AlertList",
    "NotificationToast",
    "DiagnosticsCard",
    "DecisionMatrix",
    "CompareTable",
    "ConfirmDialog",
    "ProgressStepper",
    "TimelinePanel",
    "TaskBoard",
    "WizardForm",
    "DataTable",
    "DataPreview",
    "TreeView",
    "CodeDiff",
    "CodeBlock",
    "MapView",
    "MapWithList",
    "GeoHeatmap",
    "ImageGallery",
    "InlineSvg",
    "AnimationCard",
    "AudioPlayer",
    "VideoPlayer",
    "VideoPlaylist",
    "MessageThread",
    "TranscriptView",
    "PersonCard",
    "EventList",
    "BarChart",
    "LineChart",
    "ComboChart",
    "DonutChart",
    "Sparkline",
  ],
  guardrails: [
    "Never include secrets in OpenUI Lang or context.",
    "Return only OpenUI Lang when generating popup content; no Markdown wrapper.",
    "Always define `root = ...`.",
    "Use only components listed by `prompt-spec` or `components`.",
    "Prefer explicit size presets before custom width/height.",
    "For approvals or form collection, use ConfirmDialog/FormPanel/WizardForm with actionId and open with --wait.",
    "Use the CLI for private control API calls; it attaches the per-run broker token automatically.",
    "Keep data concrete. Do not claim live external data was used unless the agent actually supplied it.",
    "Use GenUI for visual structure, not simple one-sentence answers.",
  ],
} as const;
