import { BROKER_PROTOCOL_VERSION } from "./version";

export const agentUsageGuide = {
  brokerProtocolVersion: BROKER_PROTOCOL_VERSION,
  purpose:
    "Use GenUI Popup Broker when an AI agent needs to show a local visual popup. The agent generates OpenUI Lang; the CLI/broker validates, stores, and renders it.",
  whenToUse: [
    "The user needs to inspect more than a few facts, rows, risks, options, or steps.",
    "A visual layout would make a decision, review, status report, or handoff clearer than prose.",
    "The task involves approvals, forms, checklists, diffs, maps, media, timelines, dashboards, or structured evidence.",
    "The agent should keep working in text while giving the user a separate local popup to review.",
  ],
  whenNotToUse: [
    "The answer is a single sentence or a short plain-text explanation.",
    "The user asked only for code edits, shell output, or a file change and no visual review is useful.",
    "The UI would contain secrets or sensitive data that should not be written to a local artifact.",
    "The agent cannot provide concrete data for the popup and would only show generic filler.",
  ],
  quickStart: [
    "Run `genui doctor --json` to check availability without opening a popup.",
    "Run `genui prompt-spec` for the exact OpenUI Lang syntax and component signatures.",
    "Run `genui examples` to pick a starter, or `genui examples --name build-review > ui.openui`.",
    "Use `--context-file data.json` for bulky structured data and reference it from components that support context paths.",
    "Validate with `genui validate --openui-lang-file ui.openui`.",
    "Open with `genui popup --openui-lang-file ui.openui --title \"Status\" --agent-id <agent>`.",
  ],
  preferredFlow: [
    "Run `genui prompt-spec` to learn the OpenUI Lang syntax and available components.",
    "Use `genui examples` for known-good starter OpenUI Lang.",
    "Generate OpenUI Lang in the agent. Do not send a natural-language UI request to the broker.",
    "Put bulky structured data in JSON and pass it with `--context-file`; charts and tables can read paths such as `daily` or `pages` with `contextPath` and key props.",
    "Validate the generated OpenUI Lang with `genui validate --openui-lang-file <file>`.",
    "Open the popup with `genui popup --openui-lang-file <file> --title <title> --agent-id <agent>`.",
    "Use `--wait` when the workflow needs a completion, cancellation, close, or failure result. Components with `actionId` return events in `completion.payload`.",
    "Use `genui components` for a concise component catalog.",
    "Use `genui artifacts` to inspect saved UI and `genui replay --artifact-id <artifactId>` to reopen it.",
    "Resize an open popup with `genui resize --popup-id <popupId> --size wide` or custom `--width`/`--height`.",
    "Close the popup with `genui close --popup-id <popupId>` when it is no longer useful.",
  ],
  cli: {
    agentInstructions: "genui agent-instructions",
    agentSnippet: "genui agent-snippet",
    doctor: "genui doctor --json",
    promptSpec: "genui prompt-spec",
    examples: "genui examples",
    validate: "genui validate --openui-lang-file ui.openui",
    components: "genui components",
    open:
      "genui popup --agent-id <agent> --title <title> --size review --openui-lang-file ui.openui",
    openFromStdin:
      "cat ui.openui | genui popup --agent-id <agent> --title <title> --stdin-openui",
    openAndWait:
      "genui popup --agent-id <agent> --title <title> --openui-lang-file ui.openui --wait",
    openWithContext:
      "genui popup --agent-id <agent> --title <title> --openui-lang-file ui.openui --context-file data.json",
    popups: "genui popups",
    artifacts: "genui artifacts --limit 20",
    artifact: "genui artifact --artifact-id <artifactId>",
    replay: "genui replay --artifact-id <artifactId>",
    prune: "genui prune --max-artifacts 50",
    resize: "genui resize --popup-id <popupId> --size wide",
    close: "genui close --popup-id <popupId>",
    status: "genui status",
  },
  recommendedComponents: [
    "MetricGrid",
    "Stat",
    "KeyValuePanel",
    "InsightStack",
    "AlertList",
    "Gauge",
    "ChecklistPanel",
    "NotificationToast",
    "DiagnosticsCard",
    "DecisionMatrix",
    "CompareTable",
    "ConfirmDialog",
    "ProgressStepper",
    "TimelinePanel",
    "TaskBoard",
    "WizardForm",
    "DataTable",
    "DataPreview",
    "TreeView",
    "LongText",
    "TranslationPanel",
    "TranslationCompare",
    "CodeDiff",
    "CodeBlock",
    "MapView",
    "MapWithList",
    "GeoHeatmap",
    "ImageGallery",
    "InlineSvg",
    "AnimationCard",
    "AudioPlayer",
    "VideoPlayer",
    "VideoPlaylist",
    "MessageThread",
    "TranscriptView",
    "PersonCard",
    "EventList",
    "BarChart",
    "LineChart",
    "ComboChart",
    "DonutChart",
    "Sparkline",
  ],
  guardrails: [
    "Never include secrets in OpenUI Lang or context.",
    "Return only OpenUI Lang when generating popup content; no Markdown wrapper.",
    "Always define `root = ...`.",
    "Use only components listed by `prompt-spec` or `components`.",
    "Prefer explicit size presets before custom width/height.",
    "Use `genui resize` for an already-open popup instead of reopening it when only the window size is wrong.",
    "For approvals or form collection, use ConfirmDialog/FormPanel/WizardForm with actionId and open with --wait.",
    "Use the CLI for private control API calls; it attaches the per-run broker token automatically.",
    "Keep data concrete. Do not claim live external data was used unless the agent actually supplied it.",
    "Use GenUI for visual structure, not simple one-sentence answers.",
  ],
} as const;
