export type ComponentCatalogItem = {
  name: string;
  category: string;
  description: string;
  useCases: string[];
  examplePrompt: string;
};

export const componentCatalog: ComponentCatalogItem[] = [
  {
    name: "Label",
    category: "Agent Explanation",
    description: "Reusable Liquid Glass label/badge for status, priority, count, tag, and compact text surfaces. Supports glassPreset and inkPreset.",
    useCases: ["status badge", "priority label", "tag", "count pill", "compact metadata"],
    examplePrompt: "ステータスや優先度はLabelで表示して。glassPresetも使って。",
  },
  {
    name: "MetricGrid",
    category: "Agent Explanation",
    description: "Responsive KPI/status grid for dashboards, health checks, progress summaries, and executive snapshots.",
    useCases: ["KPI dashboard", "health summary", "progress report", "risk snapshot", "agent status overview"],
    examplePrompt: "プロジェクトの状況をKPIカードで要約して。リスクと次の判断も見せて。",
  },
  {
    name: "KeyValuePanel",
    category: "Agent Explanation",
    description: "Dense facts panel for metadata, environment details, customer info, config summaries, and evidence.",
    useCases: ["metadata", "environment info", "customer facts", "config summary", "evidence"],
    examplePrompt: "この調査結果の重要メタデータをkey-value形式で整理して。",
  },
  {
    name: "InsightStack",
    category: "Agent Explanation",
    description: "High-signal takeaway stack with optional detail, confidence, source, and tone for AI reasoning and research summaries.",
    useCases: ["AI takeaways", "research findings", "evidence highlights", "executive brief", "confidence notes"],
    examplePrompt: "調査結果の要点を、根拠と信頼度つきのInsightStackで表示して。",
  },
  {
    name: "AlertList",
    category: "Agent Explanation",
    description: "Risk, blocker, warning, validation, incident, and confirmation list with severity and actions.",
    useCases: ["risks", "warnings", "blockers", "validation errors", "incident signals"],
    examplePrompt: "リスクと警告をseverity別に表示して。各項目に推奨アクションも付けて。",
  },
  {
    name: "Gauge",
    category: "Agent Explanation",
    description: "Circular bounded-value gauge for one score, confidence, health, quota, SLA, or completion percentage.",
    useCases: ["readiness score", "confidence", "health score", "quota usage", "SLA progress"],
    examplePrompt: "リリース準備度をGaugeで大きく表示して。目標値も付けて。",
  },
  {
    name: "ChecklistPanel",
    category: "Agent Explanation",
    description: "Scannable checklist for acceptance criteria, QA gates, launch readiness, requirements coverage, and review items.",
    useCases: ["acceptance criteria", "QA gates", "launch checklist", "requirements coverage", "review items"],
    examplePrompt: "リリース前チェック項目をChecklistPanelで表示して。完了・進行中・警告を分けて。",
  },
  {
    name: "ProgressStepper",
    category: "Agent Explanation",
    description: "Step-by-step progress tracker for workflows, approvals, investigations, releases, and onboarding.",
    useCases: ["workflow progress", "approval steps", "release checklist", "investigation", "onboarding"],
    examplePrompt: "この作業の進捗をステップ表示して。完了・進行中・未着手を分けて。",
  },
  {
    name: "BarChart",
    category: "Charts",
    description:
      "Horizontal bar chart for rankings, category comparison, counts, volume, cost, and risk. Can read bulky rows from --context-file by passing an empty data array and contextPath, with optional labelKey/valueKey/toneKey.",
    useCases: ["ranking", "category comparison", "counts", "cost breakdown", "risk scoring"],
    examplePrompt: "カテゴリ別の件数を棒グラフで比較して。大量データなら --context-file の pages を参照して。",
  },
  {
    name: "LineChart",
    category: "Charts",
    description:
      "Compact trend chart for time series, forecasts, backlog movement, and metric changes. Can read bulky rows from --context-file by passing an empty data array and contextPath, with optional labelKey/valueKey.",
    useCases: ["trend", "forecast", "time series", "backlog movement", "metric history"],
    examplePrompt: "直近7日の推移を折れ線グラフで表示して。大量データなら --context-file の daily を参照して。",
  },
  {
    name: "ComboChart",
    category: "Charts",
    description:
      "Combo chart with bars (left axis) and a line (right axis) sharing the X axis. Use when two related series live in different units, like PV vs. conversion rate, revenue vs. growth rate, or requests vs. latency. Can read rows from --context-file with contextPath plus labelKey/barValueKey/lineValueKey.",
    useCases: ["PV + CVR", "revenue + growth rate", "requests + latency", "calls + answered rate", "traffic + bounce rate"],
    examplePrompt: "日次PVと当日CVRを 1 枚のグラフで重ねて表示して。",
  },
  {
    name: "ResourceList",
    category: "Agent Explanation",
    description: "Clickable resource cards for files, URLs, documents, generated artifacts, and handoff references.",
    useCases: ["file links", "references", "documents", "generated artifacts", "handoff materials"],
    examplePrompt: "関連ファイルと参考URLをリソース一覧として表示して。",
  },
  {
    name: "FormPanel",
    category: "Agent Explanation",
    description: "Form/input review and lightweight editable intake panel. Set actionId to return submitted fields in completion.payload.",
    useCases: ["intake form", "approval request", "missing fields", "confirmation", "request review", "field collection"],
    examplePrompt: "入力内容をフォーム確認UIで表示して。actionIdを付けて送信結果も返して。",
  },
  {
    name: "ActionPanel",
    category: "Agent Explanation",
    description: "Prioritized next-action panel with owner, due date, severity, and optional URL handoff CTAs for agent recommendations.",
    useCases: ["next actions", "handoff", "approval workflow", "support escalation", "agent plan"],
    examplePrompt: "この調査結果から、優先度付きの次アクションをユーザーに見せて。",
  },
  {
    name: "TimelinePanel",
    category: "Agent Explanation",
    description: "Chronological timeline for incidents, launches, research, deployments, and multi-step explanations.",
    useCases: ["incident timeline", "release plan", "research history", "deployment progress", "workflow explanation"],
    examplePrompt: "障害対応の流れをタイムラインで説明して。完了・進行中・次の予定を分けて。",
  },
  {
    name: "DecisionMatrix",
    category: "Agent Explanation",
    description: "Option comparison panel for recommendations, tradeoffs, vendor/tool choices, and design decisions.",
    useCases: ["decision support", "tradeoff comparison", "tool selection", "design alternatives", "recommendation"],
    examplePrompt: "3つの実装案を比較して、推奨案と理由を視覚的に説明して。",
  },
  {
    name: "DataTable",
    category: "Agent Explanation",
    description:
      "Responsive table for operational rows, tickets, file lists, research results, rankings, and evidence. Can read records from --context-file with contextPath and infer columns when columns is empty.",
    useCases: ["ticket list", "search results", "file inventory", "ranked options", "structured evidence"],
    examplePrompt: "このJSON rowsを表で表示して。大量データなら --context-file の rows を参照して。",
  },
  {
    name: "TaskBoard",
    category: "Agent Explanation",
    description: "Compact board for task queues, implementation plans, triage lanes, QA status, and multi-agent handoffs.",
    useCases: ["task board", "agent plan", "handoff", "triage queue", "QA workflow"],
    examplePrompt: "この作業をTodo/Doing/Doneのボードで表示して。担当と状態も見せて。",
  },
  {
    name: "CodeDiff",
    category: "Agent Explanation",
    description: "Readable diff viewer for code, configuration, prompt, document, and migration review.",
    useCases: ["code review", "config diff", "patch preview", "prompt changes", "migration review"],
    examplePrompt: "この変更差分をレビュー用UIで表示して。追加・削除と確認ポイントも見せて。",
  },
  {
    name: "MapView",
    category: "Maps",
    description: "OpenStreetMap-backed map panel with center, zoom, height, and colored markers.",
    useCases: ["customer locations", "store/site maps", "routes", "incidents", "nearby places"],
    examplePrompt: "東京の顧客拠点を地図で表示して。優先度別にマーカーを分けて。",
  },
  {
    name: "MapWithList",
    category: "Maps",
    description:
      "Interactive Leaflet map paired with a clickable item list. Clicking a list entry flies the map to that point and opens its popup; clicking a marker highlights the entry. Supports pan/zoom/scroll/Retina tiles. Each item can carry optional links (official site, review pages, etc.) shown as chips in both the list and the marker popup. A Google Maps link is auto-generated from lat/lng. All links open in the user's default browser.",
    useCases: ["cafe directory", "store list with map", "tour stop browser", "customer site directory", "venue picker"],
    examplePrompt: "淡路島のおすすめカフェを地図とリスト連動で表示して。公式サイトのリンクも添えて。",
  },
  {
    name: "AudioPlayer",
    category: "Media",
    description:
      "Playlist-style audio player with one focused player and a clickable queue for music, voice notes, podcasts, recordings, and generated audio. Attempts autoplay by default where browser policy allows.",
    useCases: ["music preview", "voice note review", "meeting recordings", "podcasts", "generated speech"],
    examplePrompt: "音声メモをプレーヤーで表示して。概要と再生リストも付けて。",
  },
  {
    name: "VideoPlayer",
    category: "Media",
    description:
      "Video player with poster, chapters, transcript support, muted autoplay by default, and inline YouTube embeds for demos, clips, recordings, and walkthroughs.",
    useCases: ["YouTube embeds", "screen recordings", "feature demos", "tutorials", "incident evidence", "generated clips"],
    examplePrompt: "デモ動画をチャプター付きで表示して。重要な場面もまとめて。",
  },
  {
    name: "VideoPlaylist",
    category: "Media",
    description:
      "Recommended video playlist with a muted-autoplay main inline player and clickable candidate table. Put the best match first for automatic main playback.",
    useCases: ["YouTube recommendations", "video search results", "tutorial playlist", "demo playlist", "learning queue"],
    examplePrompt: "おすすめYouTube動画を、1本目をメイン再生、次候補をクリックで切り替えられるUIで表示して。",
  },
  {
    name: "ImageGallery",
    category: "Media",
    description: "Caption-bearing image gallery with focused preview and selectable thumbnails for screenshots, product photos, design candidates, and visual evidence.",
    useCases: ["screenshot review", "design candidates", "product photos", "visual evidence", "store/cafe imagery"],
    examplePrompt: "スクリーンショットをキャプション付きで並べて表示して。",
  },
  {
    name: "AnimationCard",
    category: "Media",
    description: "Single motion-clip card (Lottie JSON reference, looping video, animated GIF/SVG) with loop/autoplay/speed controls.",
    useCases: ["empty-state animation", "success/error animation", "onboarding hook", "branding moment", "micro-interaction"],
    examplePrompt: "成功時のアニメーションを表示して。Lottie JSONを使って。",
  },
  {
    name: "ConfirmDialog",
    category: "Decisions",
    description: "Single high-stakes confirmation card with accept/decline actions, risk level, and optional actionId completion payload.",
    useCases: ["delete confirmation", "deploy approval", "destructive action gate", "autonomous-agent permission", "irreversible step"],
    examplePrompt: "この削除操作の確認ダイアログを表示して。リスクと結果も明記して。",
  },
  {
    name: "CompareTable",
    category: "Decisions",
    description: "Side-by-side option comparison with shared specs across columns. Use for plan/tier/library/API picks.",
    useCases: ["plan comparison", "library evaluation", "API alternatives", "vendor selection", "tier selection"],
    examplePrompt: "3つの料金プランを並べて、機能と価格を比較表で表示して。",
  },
  {
    name: "QuickActions",
    category: "Decisions",
    description: "Tile-style shortcut row for fast picking with optional URL links. No per-item description — pair with ActionPanel for details.",
    useCases: ["dashboard shortcuts", "command palette", "frequent operations", "home tiles", "navigation buttons"],
    examplePrompt: "よく使う4つの操作をタイル状のショートカットで表示して。",
  },
  {
    name: "CodeBlock",
    category: "Code & Data",
    description: "Highlighted code or command snippet with filename, language label, line numbers, and runnable hint. Use for paste-and-run answers.",
    useCases: ["command to run", "code snippet", "config example", "shell one-liner", "API call sample", "small diff"],
    examplePrompt: "このコマンドをCodeBlockで表示して。runnableフラグも付けて。",
  },
  {
    name: "DataPreview",
    category: "Code & Data",
    description:
      "Developer preview of raw structured data: column types and the first N rows. Use for SQL results, CSV head, JSON samples. Can read records from --context-file with contextPath and infer schema.",
    useCases: ["SQL result", "CSV head", "JSON sample", "API response preview", "schema check"],
    examplePrompt: "このSQLクエリ結果のスキーマと先頭5行をDataPreviewで表示して。",
  },
  {
    name: "LongText",
    category: "Text & Translation",
    description:
      "Readable long-form text viewer for articles, specs, policies, transcripts, legal copy, and generated drafts. Supports sections, source/language labels, and bounded scrolling.",
    useCases: ["long article", "policy text", "spec review", "transcript", "generated draft"],
    examplePrompt: "この長文ドラフトを見出しごとに読みやすく表示して。出典と言語も付けて。",
  },
  {
    name: "TranslationPanel",
    category: "Text & Translation",
    description:
      "Focused translation review panel with source/target language labels, translated text, optional source excerpt, notes, and glossary terms.",
    useCases: ["translation result", "glossary review", "localization note", "single translated text", "source excerpt"],
    examplePrompt: "この日本語文の英訳を表示して。用語集と翻訳メモも付けて。",
  },
  {
    name: "TranslationCompare",
    category: "Text & Translation",
    description:
      "Side-by-side translation comparison by segment. Use for bilingual QA, localization review, wording checks, and before/after translation edits.",
    useCases: ["bilingual comparison", "translation QA", "localization review", "wording check", "before/after translation"],
    examplePrompt: "原文と翻訳を左右で段落ごとに比較して。要確認箇所にreviewを付けて。",
  },
  {
    name: "TreeView",
    category: "Code & Data",
    description: "Indented hierarchy view for file trees, JSON shape, org charts, dependency trees, and nested config.",
    useCases: ["file tree", "JSON structure", "org chart", "dependency tree", "nested config"],
    examplePrompt: "このディレクトリ構造をTreeViewで表示して。",
  },
  {
    name: "WeatherCard",
    category: "Schedule & People",
    description: "Today/forecast weather card with temperature, summary, optional hourly/daily forecast.",
    useCases: ["today's weather", "hourly forecast", "daily forecast", "atmosphere conditions"],
    examplePrompt: "今日の東京の天気と6時間先までの予報を表示して。",
  },
  {
    name: "EventList",
    category: "Schedule & People",
    description: "Today/upcoming events agenda with times, locations, attendees, and notes.",
    useCases: ["meeting agenda", "release schedule", "today's events", "news-of-the-day", "calendar handoff"],
    examplePrompt: "今日の会議予定を時刻順に並べて表示して。",
  },
  {
    name: "PersonCard",
    category: "Schedule & People",
    description: "People / contact card grid: name, role, avatar, contact channels, presence status.",
    useCases: ["team intro", "reviewer list", "owner handoff", "on-call contacts", "attendee directory"],
    examplePrompt: "チームメンバーの担当と連絡先をカードで表示して。",
  },
  {
    name: "DiagnosticsCard",
    category: "Diagnostics",
    description: "Named checks each with pass|warn|fail|skip|pending. Use for CI status, env probes, deploy gates, lint/types/tests rollups.",
    useCases: ["CI status", "env diagnostics", "deploy gate", "pre-flight checks", "lint/types/tests rollup"],
    examplePrompt: "CIのテスト・lint・typesの結果をDiagnosticsCardで表示して。",
  },
  {
    name: "TranscriptView",
    category: "Conversations",
    description: "Conversation log view distinguishing user/agent/system/human roles with timestamps.",
    useCases: ["support ticket replay", "agent-to-agent log", "meeting notes", "LLM dialog dump", "interview transcript"],
    examplePrompt: "サポート対応の会話ログをTranscriptViewで表示して。",
  },
  {
    name: "DonutChart",
    category: "Charts",
    description: "Donut/pie composition chart for share/breakdown data where parts sum to a whole.",
    useCases: ["capacity by team", "traffic by source", "test outcome share", "category share", "budget split"],
    examplePrompt: "ストレージ使用量の内訳をDonutChartで表示して。",
  },
  {
    name: "WizardForm",
    category: "Diagnostics & Workflow",
    description: "Interactive multi-step wizard with per-step fields and optional actionId completion payload.",
    useCases: ["onboarding wizard", "setup flow", "multi-stage approval", "configuration steps", "guided form"],
    examplePrompt: "設定手順をWizardFormで表示して。最後に入力内容をagentへ返して。",
  },
  {
    name: "InlineSvg",
    category: "Vector",
    description: "Inline SVG renderer for vector diagrams, schematics, logos, icons, and hand-drawn illustrations. svg is a full <svg>…</svg> string; <script> and on* handlers are stripped.",
    useCases: ["vector diagram", "logo", "icon", "schematic", "generated illustration"],
    examplePrompt: "ロゴをSVGで表示して。色はブルー基調で。",
  },
  {
    name: "MessageThread",
    category: "Conversation",
    description: "Chat-style message thread with role-aligned bubbles (user right, others left) for LLM dialogs, support chats, and agent-to-agent exchanges. Supports an optional composer row.",
    useCases: ["LLM dialog preview", "support chat", "agent-to-agent exchange", "ticket replay", "reviewer dialog"],
    examplePrompt: "カスタマーサポートのチャット履歴をチャット形式で表示して。",
  },
  {
    name: "MessageBubble",
    category: "Conversation",
    description: "Single chat bubble for one user/assistant/agent/tool message. Use for quoted snippets or a single most-recent reply.",
    useCases: ["last reply preview", "quoted message", "single agent response", "single tool output"],
    examplePrompt: "最新の返信を1つだけチャットバブルで見せて。",
  },
  {
    name: "Stat",
    category: "Hero KPI",
    description: "Single hero KPI: one large value with optional delta, target, sparkline, and footnote. Use when one number dominates.",
    useCases: ["today's revenue", "primary SLA", "main error rate", "headline metric", "hero KPI"],
    examplePrompt: "今日の売上を大きく1つだけ見せて。前日比とミニトレンドも付けて。",
  },
  {
    name: "Sparkline",
    category: "Hero KPI",
    description: "Tiny inline trend line with no axes — great next to a value or label. For full charts use LineChart.",
    useCases: ["inline trend", "row-level mini chart", "header sparkline", "value badge trend"],
    examplePrompt: "数字の横に小さなトレンドラインだけ表示して。",
  },
  {
    name: "GeoHeatmap",
    category: "Region Maps",
    description: "Region-shaded heatmap (states, prefectures, countries) as a tiled grid colored by value. Use for share/density/coverage where MapView pins would be too noisy.",
    useCases: ["prefecture share", "state coverage", "country density", "regional KPI breakdown", "territory load"],
    examplePrompt: "都道府県別の売上シェアをヒートマップで表示して。",
  },
  {
    name: "NotificationToast",
    category: "Notifications",
    description: "Slim banner-style notification for success/warning/error/info with optional icon, time, single CTA, and dismiss label.",
    useCases: ["deploy success", "save confirmation", "error banner", "warning strip", "single-line status"],
    examplePrompt: "デプロイ成功の通知バナーを表示して。リリースノートへのリンクも付けて。",
  },
];
