export type GenUIExample = {
  name: string;
  title: string;
  description: string;
  size: "compact" | "card" | "panel" | "default" | "wide" | "tall" | "stage" | "cinema" | "fullscreen";
  openuiLang: string;
};

export const genUIExamples: GenUIExample[] = [
  {
    name: "build-review",
    title: "Build Review",
    description: "Status summary with checks and recommended next action.",
    size: "panel",
    openuiLang: [
      "root = Card([header, metrics, diagnostics, actions])",
      'header = CardHeader("Build Review", "Current agent run")',
      'metrics = MetricGrid("Summary", "Key signals", [m1, m2, m3])',
      'm1 = { label: "Tests", value: "68 passed", tone: "positive", description: "Unit suite completed" }',
      'm2 = { label: "Lint", value: "passed", tone: "positive", description: "ESLint reported no issues" }',
      'm3 = { label: "Build", value: "ready", tone: "info", description: "Electron build is available" }',
      'diagnostics = DiagnosticsCard("Checks", "Pre-flight status", [c1, c2, c3])',
      'c1 = { name: "tests", status: "pass", detail: "68 passed" }',
      'c2 = { name: "lint", status: "pass", detail: "clean" }',
      'c3 = { name: "electron:build", status: "pass", detail: "tsc completed" }',
      'actions = ActionPanel("Next Actions", "Recommended handoff", [a1])',
      'a1 = { label: "Open review popup", priority: "medium", owner: "agent", description: "Share this status with the user" }',
    ].join("\n"),
  },
  {
    name: "decision-review",
    title: "Decision Review",
    description: "Comparison matrix for choosing an implementation direction.",
    size: "wide",
    openuiLang: [
      "root = Card([header, matrix, actions])",
      'header = CardHeader("Decision Review", "Choose the implementation direction")',
      'matrix = DecisionMatrix("Options", "Tradeoffs and recommendation", [o1, o2, o3])',
      'o1 = { name: "Direct OpenUI Lang", recommendation: "recommended", score: "9/10", pros: ["Clear responsibility", "No broker LLM"], cons: ["Agent must generate UI"] }',
      'o2 = { name: "Broker prompt route", recommendation: "avoid", score: "4/10", pros: ["Simple caller"], cons: ["Duplicate interpretation", "Harder to control"] }',
      'o3 = { name: "Manual screenshots", recommendation: "consider", score: "5/10", pros: ["Predictable"], cons: ["Not generative", "Hard to update"] }',
      'actions = ActionPanel("Next Actions", "Recommended path", [a1])',
      'a1 = { label: "Use direct CLI route", priority: "high", owner: "agent", description: "Generate OpenUI Lang and pass it to --openui-lang-file" }',
    ].join("\n"),
  },
  {
    name: "incident-timeline",
    title: "Incident Timeline",
    description: "Timeline plus risks for incident communication.",
    size: "tall",
    openuiLang: [
      "root = Card([header, timeline, alerts, actions])",
      'header = CardHeader("Incident Timeline", "Current response state")',
      'timeline = TimelinePanel("Timeline", "Response milestones", [t1, t2, t3])',
      't1 = { time: "09:00", title: "Alert fired", status: "done", description: "Monitoring detected elevated errors" }',
      't2 = { time: "09:12", title: "Owner paged", status: "done", description: "Runtime owner acknowledged" }',
      't3 = { time: "09:30", title: "Mitigation active", status: "active", description: "Traffic is being shifted" }',
      'alerts = AlertList("Risks", "Items to watch", [r1, r2])',
      'r1 = { title: "Customer impact", severity: "warning", description: "Checkout latency remains elevated", action: "Keep status page updated" }',
      'r2 = { title: "Rollback window", severity: "info", description: "Rollback remains available", action: "Confirm data safety before rollback" }',
      'actions = ActionPanel("Next Actions", "Immediate handoff", [a1])',
      'a1 = { label: "Post next update", priority: "high", owner: "incident lead", due: "15 min", description: "Summarize current mitigation and ETA" }',
    ].join("\n"),
  },
  {
    name: "data-table",
    title: "Triage Table",
    description: "Structured rows with a follow-up action.",
    size: "wide",
    openuiLang: [
      "root = Card([header, table, actions])",
      'header = CardHeader("Triage Table", "Open support items")',
      'table = DataTable("Tickets", "Prioritized queue", [col1, col2, col3], [row1, row2], "Agent-selected rows")',
      'col1 = { key: "id", label: "ID" }',
      'col2 = { key: "status", label: "Status" }',
      'col3 = { key: "next", label: "Next action" }',
      'row1 = { id: "A-1", status: "blocked", next: "Escalate owner" }',
      'row2 = { id: "A-2", status: "ready", next: "Notify reviewer" }',
      'actions = ActionPanel("Next Actions", "Queue handoff", [a1])',
      'a1 = { label: "Escalate blocked ticket", priority: "high", owner: "support", description: "A-1 needs an owner decision" }',
    ].join("\n"),
  },
  {
    name: "code-review",
    title: "Code Review",
    description: "Review summary with changed files, risks, and follow-up tasks.",
    size: "wide",
    openuiLang: [
      "root = Card([header, metrics, diff, alerts, board])",
      'header = CardHeader("Code Review", "Patch readiness snapshot")',
      'metrics = MetricGrid("Review Signals", "Automated and manual gates", [m1, m2, m3])',
      'm1 = { label: "Tests", value: "37 passed", tone: "positive", description: "Unit suite is green" }',
      'm2 = { label: "Risk", value: "medium", tone: "warning", description: "Touches CLI and API contracts" }',
      'm3 = { label: "Docs", value: "updated", tone: "positive", description: "Agent guide aligned" }',
      'diff = CodeDiff("Key Diff", "Representative change for review", [file1])',
      'file1 = { path: "scripts/genui-cli.ts", language: "ts", additions: 4, deletions: 1, hunks: [hunk1] }',
      'hunk1 = { title: "add replay command", lines: [d1, d2, d3] }',
      'd1 = { type: "context", content: "if (command === \\"status\\") return status(options)" }',
      'd2 = { type: "add", content: "if (command === \\"replay\\") return replay(options)" }',
      'd3 = { type: "add", content: "if (command === \\"artifacts\\") return artifacts(options)" }',
      'alerts = AlertList("Review Notes", "Items to confirm before merge", [r1])',
      'r1 = { title: "Protocol compatibility", severity: "warning", description: "New fields should remain additive for existing clients", action: "Keep response fields backward compatible" }',
      'board = TaskBoard("Follow-up", "Owner handoff", [todo, done])',
      'todo = { title: "Todo", tone: "warning", items: [t1] }',
      'done = { title: "Done", tone: "positive", items: [t2] }',
      't1 = { title: "Visual QA", owner: "agent", status: "next", description: "Check dashboard at desktop and narrow widths" }',
      't2 = { title: "Regression tests", owner: "agent", status: "done", description: "Examples stay parser-valid" }',
    ].join("\n"),
  },
  {
    name: "research-brief",
    title: "Research Brief",
    description: "Evidence summary with sources, confidence, and decision next steps.",
    size: "wide",
    openuiLang: [
      "root = Card([header, facts, sources, matrix, actions])",
      'header = CardHeader("Research Brief", "Evidence and recommendation")',
      'facts = KeyValuePanel("Findings", "Condensed facts for the user", [f1, f2, f3])',
      'f1 = { label: "Question", value: "Which integration path is practical?", tone: "info", description: "Compare CLI-first vs API-first usage" }',
      'f2 = { label: "Confidence", value: "high", tone: "positive", description: "Sources agree on the supported flow" }',
      'f3 = { label: "Gap", value: "examples", tone: "warning", description: "More starter snippets reduce authoring mistakes" }',
      'sources = ResourceList("Sources", "References used by the agent", [s1, s2, s3])',
      's1 = { title: "README", type: "doc", status: "ready", description: "Current CLI and broker contract" }',
      's2 = { title: "docs/agent-interface.md", type: "doc", status: "ready", description: "Agent-facing workflow" }',
      's3 = { title: "src/server/genui/component-catalog.ts", type: "code", status: "ready", description: "Allowed components and use cases" }',
      'matrix = DecisionMatrix("Recommendation", "Choose the next implementation step", [o1, o2])',
      'o1 = { name: "Artifact replay", recommendation: "recommended", score: "9/10", pros: ["Immediate reuse", "Better debugging"], cons: ["Requires new API"] }',
      'o2 = { name: "More visual themes", recommendation: "defer", score: "5/10", pros: ["Nice polish"], cons: ["Less agent workflow value"] }',
      'actions = ActionPanel("Next Actions", "Research handoff", [a1])',
      'a1 = { label: "Implement replay", priority: "high", owner: "agent", description: "Expose inspect and replay in CLI and dashboard" }',
    ].join("\n"),
  },
  {
    name: "support-triage",
    title: "Support Triage",
    description: "Ticket context, conversation excerpt, risk, and escalation plan.",
    size: "wide",
    openuiLang: [
      "root = Card([header, metrics, transcript, tickets, actions])",
      'header = CardHeader("Support Triage", "Customer issue and next response")',
      'metrics = MetricGrid("Queue Health", "Current triage signals", [m1, m2, m3])',
      'm1 = { label: "Severity", value: "S2", tone: "warning", description: "Billing workflow affected" }',
      'm2 = { label: "Age", value: "42m", tone: "info", description: "Within first-response SLA" }',
      'm3 = { label: "Owner", value: "support", tone: "neutral", description: "Needs engineering confirmation" }',
      'transcript = TranscriptView("Conversation", "Latest messages", [msg1, msg2, msg3])',
      'msg1 = { speaker: "Customer", role: "human", time: "10:12", text: "Invoices are not exporting for workspace W-42." }',
      'msg2 = { speaker: "Agent", role: "agent", time: "10:14", text: "I found repeated export_403 errors after the permission migration." }',
      'msg3 = { speaker: "Support", role: "user", time: "10:18", text: "Please confirm whether this is safe to retry." }',
      'tickets = DataTable("Tickets", "Related queue rows", [col1, col2, col3], [row1, row2], "Escalate S2 first")',
      'col1 = { key: "id", label: "Ticket" }',
      'col2 = { key: "status", label: "Status" }',
      'col3 = { key: "next", label: "Next" }',
      'row1 = { id: "SUP-418", status: "waiting-on-agent", next: "Confirm retry safety" }',
      'row2 = { id: "SUP-419", status: "new", next: "Check same error signature" }',
      'actions = ActionPanel("Next Actions", "Response plan", [a1, a2])',
      'a1 = { label: "Ask engineering", priority: "high", owner: "support", due: "now", description: "Confirm permission retry behavior" }',
      'a2 = { label: "Draft customer update", priority: "medium", owner: "agent", due: "15m", description: "Share status and workaround if safe" }',
    ].join("\n"),
  },
  {
    name: "data-quality",
    title: "Data Quality",
    description: "Raw data preview with schema, anomalies, and cleanup actions.",
    size: "wide",
    openuiLang: [
      "root = Card([header, preview, diagnostics, actions])",
      'header = CardHeader("Data Quality", "Import validation snapshot")',
      'preview = DataPreview("CSV Head", "First rows and inferred schema", "customers.csv", [s1, s2, s3], [r1, r2, r3], true, 1284)',
      's1 = { name: "customer_id", type: "string", nullable: false }',
      's2 = { name: "email", type: "string", nullable: true }',
      's3 = { name: "plan", type: "string", nullable: false }',
      'r1 = { customer_id: "C-001", email: "ops@example.com", plan: "pro" }',
      'r2 = { customer_id: "C-002", email: "", plan: "enterprise" }',
      'r3 = { customer_id: "C-003", email: "bad-email", plan: "free" }',
      'diagnostics = DiagnosticsCard("Validation", "Import checks", [c1, c2, c3])',
      'c1 = { name: "schema", status: "pass", detail: "3 expected columns present" }',
      'c2 = { name: "email format", status: "warn", detail: "31 rows need review" }',
      'c3 = { name: "plan enum", status: "pass", detail: "all values recognized" }',
      'actions = ActionPanel("Next Actions", "Cleanup workflow", [a1, a2])',
      'a1 = { label: "Export invalid rows", priority: "high", owner: "data", description: "Review blank or malformed email values" }',
      'a2 = { label: "Proceed after review", priority: "medium", owner: "agent", description: "Re-run validation before import" }',
    ].join("\n"),
  },
];

export function getGenUIExample(name: string): GenUIExample | undefined {
  return genUIExamples.find((example) => example.name === name);
}
